/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workspaces Route */
        get: operations["list_workspaces_route_api_v1_workspaces_get"];
        put?: never;
        /** Create Workspace Route */
        post: operations["create_workspace_route_api_v1_workspaces_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/artifacts/{artifact_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Artifact Content Route
         * @description Serve an artifact's raw file content (e.g. the report JSON, with its
         *     embedded slide deck) so the frontend can render or download it --
         *     ``storage_uri`` alone is a ``file://`` URI a browser can't fetch.
         */
        get: operations["get_artifact_content_route_api_v1_workspaces__workspace_id__artifacts__artifact_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Audit Events Route */
        get: operations["search_audit_events_route_api_v1_workspaces__workspace_id__audit_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/knowledge/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents Route */
        get: operations["list_documents_route_api_v1_workspaces__workspace_id__knowledge_documents_get"];
        put?: never;
        /** Ingest Document Route */
        post: operations["ingest_document_route_api_v1_workspaces__workspace_id__knowledge_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/missions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Missions Route */
        get: operations["list_missions_route_api_v1_workspaces__workspace_id__missions_get"];
        put?: never;
        /** Create Mission Route */
        post: operations["create_mission_route_api_v1_workspaces__workspace_id__missions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/missions/{mission_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Mission Route */
        get: operations["get_mission_route_api_v1_workspaces__workspace_id__missions__mission_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/missions/{mission_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Artifacts Route */
        get: operations["list_artifacts_route_api_v1_workspaces__workspace_id__missions__mission_id__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/missions/{mission_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Mission Runs Route */
        get: operations["list_mission_runs_route_api_v1_workspaces__workspace_id__missions__mission_id__runs_get"];
        put?: never;
        /** Start Run Route */
        post: operations["start_run_route_api_v1_workspaces__workspace_id__missions__mission_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Route */
        get: operations["get_run_route_api_v1_workspaces__workspace_id__runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/runs/{run_id}/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Approval Route */
        post: operations["resolve_approval_route_api_v1_workspaces__workspace_id__runs__run_id__approvals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run Route */
        post: operations["cancel_run_route_api_v1_workspaces__workspace_id__runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Run Events Route
         * @description Server-sent events for one run's audit trail (ARCHITECTURE.md section
         *     11), tailing the Redis Stream ``RedisEventBusSink`` publishes to.
         *     Reconnecting clients replay up to the stream's retained window (see
         *     ``RedisEventBusSink.STREAM_MAXLEN``) by starting from id "0".
         */
        get: operations["stream_run_events_route_api_v1_workspaces__workspace_id__runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/runs/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Run Route */
        post: operations["resume_run_route_api_v1_workspaces__workspace_id__runs__run_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service health */
        get: operations["get_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApprovalDecisionRequest */
        ApprovalDecisionRequest: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "approve" | "reject";
            /** Reason */
            reason?: string | null;
        };
        /** ArtifactResponse */
        ArtifactResponse: {
            /** Artifact Type */
            artifact_type: string;
            /** Checksum */
            checksum: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Run Id */
            run_id: string | null;
            /** Storage Uri */
            storage_uri: string;
        };
        /** AuditEventResponse */
        AuditEventResponse: {
            /** Actor */
            actor: string;
            /** Event Type */
            event_type: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Mission Id
             * Format: uuid
             */
            mission_id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Status */
            status: string;
            /** Task Id */
            task_id: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Environment */
            environment: string;
            /** Service */
            service: string;
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** KnowledgeDocumentCreateRequest */
        KnowledgeDocumentCreateRequest: {
            /** Source Metadata */
            source_metadata?: {
                [key: string]: unknown;
            };
            /** Source Uri */
            source_uri: string;
            /** Text */
            text: string;
        };
        /** KnowledgeDocumentResponse */
        KnowledgeDocumentResponse: {
            /** Checksum */
            checksum: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ingestion Status */
            ingestion_status: string;
            /** Source Uri */
            source_uri: string;
        };
        /** MissionCreateRequest */
        MissionCreateRequest: {
            /** Constraints */
            constraints?: string[];
            /** Context */
            context?: {
                [key: string]: unknown;
            };
            /** Objective */
            objective: string;
            /** Raw Request */
            raw_request: string;
            /** Success Criteria */
            success_criteria?: string[];
        };
        /** MissionResponse */
        MissionResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Raw Request */
            raw_request: string;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /** RunDetailResponse */
        RunDetailResponse: {
            /** Approval */
            approval?: {
                [key: string]: unknown;
            } | null;
            /** Compliance Result */
            compliance_result?: {
                [key: string]: unknown;
            } | null;
            /** Escalation */
            escalation?: {
                [key: string]: unknown;
            } | null;
            /** Final Report */
            final_report?: {
                [key: string]: unknown;
            } | null;
            /** Last Error */
            last_error?: {
                [key: string]: unknown;
            } | null;
            /**
             * Mission Id
             * Format: uuid
             */
            mission_id: string;
            /** Plan */
            plan?: {
                [key: string]: unknown;
            } | null;
            /** Qa Result */
            qa_result?: {
                [key: string]: unknown;
            } | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Status */
            status: string;
            /** Tasks */
            tasks?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            } | null;
        };
        /** RunStartResponse */
        RunStartResponse: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Status */
            status: string;
        };
        /**
         * RunSummaryResponse
         * @description A run history row -- the lightweight Postgres projection
         *     (ARCHITECTURE.md §6), kept in sync opportunistically. Use
         *     ``RunDetailResponse`` for the authoritative live state of one run.
         */
        RunSummaryResponse: {
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Summary */
            error_summary: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkspaceCreateRequest */
        WorkspaceCreateRequest: {
            /** Name */
            name: string;
        };
        /** WorkspaceResponse */
        WorkspaceResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_workspaces_route_api_v1_workspaces_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Aegis-Identity-Subject"?: string | null;
                "X-Aegis-Display-Name"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_workspace_route_api_v1_workspaces_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Aegis-Identity-Subject"?: string | null;
                "X-Aegis-Display-Name"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_content_route_api_v1_workspaces__workspace_id__artifacts__artifact_id__content_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Aegis-Identity-Subject"?: string | null;
                "X-Aegis-Display-Name"?: string | null;
            };
            path: {
                workspace_id: string;
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_audit_events_route_api_v1_workspaces__workspace_id__audit_events_get: {
        parameters: {
            query?: {
                run_id?: string | null;
                event_type?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "X-Aegis-Identity-Subject"?: string | null;
                "X-Aegis-Display-Name"?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_route_api_v1_workspaces__workspace_id__knowledge_documents_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Aegis-Identity-Subject"?: string | null;
                "X-Aegis-Display-Name"?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeDocumentResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_document_route_api_v1_workspaces__workspace_id__knowledge_documents_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Aegis-Identity-Subject"?: string | null;
                "X-Aegis-Display-Name"?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeDocumentCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_missions_route_api_v1_workspaces__workspace_id__missions_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Aegis-Identity-Subject"?: string | null;
                "X-Aegis-Display-Name"?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_mission_route_api_v1_workspaces__workspace_id__missions_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Aegis-Identity-Subject"?: string | null;
                "X-Aegis-Display-Name"?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MissionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_mission_route_api_v1_workspaces__workspace_id__missions__mission_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Aegis-Identity-Subject"?: string | null;
                "X-Aegis-Display-Name"?: string | null;
            };
            path: {
                workspace_id: string;
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_artifacts_route_api_v1_workspaces__workspace_id__missions__mission_id__artifacts_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Aegis-Identity-Subject"?: string | null;
                "X-Aegis-Display-Name"?: string | null;
            };
            path: {
                workspace_id: string;
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_mission_runs_route_api_v1_workspaces__workspace_id__missions__mission_id__runs_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Aegis-Identity-Subject"?: string | null;
                "X-Aegis-Display-Name"?: string | null;
            };
            path: {
                workspace_id: string;
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummaryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_route_api_v1_workspaces__workspace_id__missions__mission_id__runs_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Aegis-Identity-Subject"?: string | null;
                "X-Aegis-Display-Name"?: string | null;
            };
            path: {
                workspace_id: string;
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_route_api_v1_workspaces__workspace_id__runs__run_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Aegis-Identity-Subject"?: string | null;
                "X-Aegis-Display-Name"?: string | null;
            };
            path: {
                workspace_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_approval_route_api_v1_workspaces__workspace_id__runs__run_id__approvals_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Aegis-Identity-Subject"?: string | null;
                "X-Aegis-Display-Name"?: string | null;
            };
            path: {
                workspace_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_route_api_v1_workspaces__workspace_id__runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Aegis-Identity-Subject"?: string | null;
                "X-Aegis-Display-Name"?: string | null;
            };
            path: {
                workspace_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_events_route_api_v1_workspaces__workspace_id__runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Aegis-Identity-Subject"?: string | null;
                "X-Aegis-Display-Name"?: string | null;
            };
            path: {
                workspace_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_run_route_api_v1_workspaces__workspace_id__runs__run_id__resume_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Aegis-Identity-Subject"?: string | null;
                "X-Aegis-Display-Name"?: string | null;
            };
            path: {
                workspace_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
