// Generated from the FastAPI app's OpenAPI schema (ARCHITECTURE.md section 9:
// "OpenAPI is generated by FastAPI and is the source for TypeScript client
// generation") -- do not hand-edit api-types.ts. Regenerate it with
// `npm run generate:api-types` from the repo root after activating
// apps/api/.venv (see README.md), which re-exports the live schema to
// packages/shared/openapi.json before running the TypeScript generator.
export type { components, operations, paths } from "./api-types";

import type { components } from "./api-types";

export type HealthResponse = components["schemas"]["HealthResponse"];

export type WorkspaceCreateRequest = components["schemas"]["WorkspaceCreateRequest"];
export type WorkspaceResponse = components["schemas"]["WorkspaceResponse"];

export type MissionCreateRequest = components["schemas"]["MissionCreateRequest"];
export type MissionResponse = components["schemas"]["MissionResponse"];

export type RunStartResponse = components["schemas"]["RunStartResponse"];
export type RunSummaryResponse = components["schemas"]["RunSummaryResponse"];
export type RunDetailResponse = components["schemas"]["RunDetailResponse"];
export type ApprovalDecisionRequest = components["schemas"]["ApprovalDecisionRequest"];

export type ArtifactResponse = components["schemas"]["ArtifactResponse"];
export type AuditEventResponse = components["schemas"]["AuditEventResponse"];

export type KnowledgeDocumentCreateRequest =
  components["schemas"]["KnowledgeDocumentCreateRequest"];
export type KnowledgeDocumentResponse = components["schemas"]["KnowledgeDocumentResponse"];
