"""initial schema

Revision ID: 48db649e4ba5
Revises: 
Create Date: 2026-09-14 19:43:07.251444

"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '48db649e4ba5'
down_revision: str | None = None
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # pgvector is the Day-1 default vector store (ARCHITECTURE.md section 8).
    # Guarded rather than unconditional: this migration is authored for
    # PostgreSQL, but autogeneration tooling may run `alembic` against a
    # throwaway SQLite DB to diff future revisions (see infra/docker/postgres
    # for the equivalent bootstrap used by fresh Postgres containers).
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('mission_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_mission_id'), 'audit_events', ['mission_id'], unique=False)
    op.create_index(op.f('ix_audit_events_occurred_at'), 'audit_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_events_run_id'), 'audit_events', ['run_id'], unique=False)
    op.create_index(op.f('ix_audit_events_task_id'), 'audit_events', ['task_id'], unique=False)
    op.create_table('users',
    sa.Column('identity_subject', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_identity_subject'), 'users', ['identity_subject'], unique=True)
    op.create_table('workspaces',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=True)
    op.create_table('knowledge_documents',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('source_uri', sa.String(length=500), nullable=False),
    sa.Column('source_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('ingestion_status', sa.Enum('pending', 'ingesting', 'ready', 'failed', name='ingestion_status'), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_documents_workspace_id'), 'knowledge_documents', ['workspace_id'], unique=False)
    op.create_table('missions',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('raw_request', sa.Text(), nullable=False),
    sa.Column('normalized_request', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'planned', 'running', 'completed', 'failed', 'cancelled', name='mission_status'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_workspace_id'), 'missions', ['workspace_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'operator', 'reviewer', 'viewer', name='workspace_role'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_member')
    )
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('chunk_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_knowledge_chunk_index')
    )
    op.create_index(op.f('ix_knowledge_chunks_document_id'), 'knowledge_chunks', ['document_id'], unique=False)
    op.create_table('mission_plans',
    sa.Column('mission_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('plan', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_approval', 'approved', 'rejected', 'superseded', name='plan_status'), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_id', 'version', name='uq_mission_plan_version')
    )
    op.create_index(op.f('ix_mission_plans_mission_id'), 'mission_plans', ['mission_id'], unique=False)
    op.create_table('plan_steps',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('agent_role', sa.Enum('orchestrator', 'research', 'data', 'analyst', 'qa', 'compliance', 'report', name='agent_role'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('dependencies', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('input', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('acceptance_criteria', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'cancelled', name='task_status'), nullable=False),
    sa.Column('result_id', sa.Uuid(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['mission_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_steps_plan_id'), 'plan_steps', ['plan_id'], unique=False)
    op.create_table('runs',
    sa.Column('mission_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=True),
    sa.Column('graph_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('running', 'paused', 'awaiting_approval', 'awaiting_escalation', 'cancel_requested', 'cancelled', 'completed', 'failed', name='run_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['mission_plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_mission_id'), 'runs', ['mission_id'], unique=False)
    op.create_index(op.f('ix_runs_plan_id'), 'runs', ['plan_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('mission_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('storage_uri', sa.String(length=500), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=False),
    sa.Column('artifact_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_mission_id'), 'artifacts', ['mission_id'], unique=False)
    op.create_index(op.f('ix_artifacts_run_id'), 'artifacts', ['run_id'], unique=False)
    op.create_table('compliance_reviews',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('finding_id', sa.Uuid(), nullable=True),
    sa.Column('report_id', sa.Uuid(), nullable=True),
    sa.Column('rule_set_version', sa.String(length=50), nullable=False),
    sa.Column('verdict', sa.Enum('pass', 'escalate', 'reject', name='compliance_verdict'), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('escalation_reference', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_reviews_run_id'), 'compliance_reviews', ['run_id'], unique=False)
    op.create_table('run_checkpoints',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('node_name', sa.String(length=100), nullable=False),
    sa.Column('state_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'sequence', name='uq_run_checkpoint_sequence')
    )
    op.create_index(op.f('ix_run_checkpoints_run_id'), 'run_checkpoints', ['run_id'], unique=False)
    op.create_table('tool_executions',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('tool_version', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', name='tool_risk_level'), nullable=False),
    sa.Column('input_sanitized', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('output_sanitized', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'failed', 'denied', name='tool_execution_status'), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_executions_run_id'), 'tool_executions', ['run_id'], unique=False)
    op.create_index(op.f('ix_tool_executions_task_id'), 'tool_executions', ['task_id'], unique=False)
    op.create_table('code_executions',
    sa.Column('tool_execution_id', sa.Uuid(), nullable=True),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('script_hash', sa.String(length=64), nullable=False),
    sa.Column('resource_usage', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('exit_status', sa.Integer(), nullable=True),
    sa.Column('stdout_redacted', sa.Text(), nullable=True),
    sa.Column('stderr_redacted', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_execution_id'], ['tool_executions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_executions_run_id'), 'code_executions', ['run_id'], unique=False)
    op.create_index(op.f('ix_code_executions_task_id'), 'code_executions', ['task_id'], unique=False)
    op.create_index(op.f('ix_code_executions_tool_execution_id'), 'code_executions', ['tool_execution_id'], unique=False)
    op.create_table('sql_queries',
    sa.Column('tool_execution_id', sa.Uuid(), nullable=True),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('target_schema', sa.String(length=200), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_execution_id'], ['tool_executions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sql_queries_run_id'), 'sql_queries', ['run_id'], unique=False)
    op.create_index(op.f('ix_sql_queries_task_id'), 'sql_queries', ['task_id'], unique=False)
    op.create_index(op.f('ix_sql_queries_tool_execution_id'), 'sql_queries', ['tool_execution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sql_queries_tool_execution_id'), table_name='sql_queries')
    op.drop_index(op.f('ix_sql_queries_task_id'), table_name='sql_queries')
    op.drop_index(op.f('ix_sql_queries_run_id'), table_name='sql_queries')
    op.drop_table('sql_queries')
    op.drop_index(op.f('ix_code_executions_tool_execution_id'), table_name='code_executions')
    op.drop_index(op.f('ix_code_executions_task_id'), table_name='code_executions')
    op.drop_index(op.f('ix_code_executions_run_id'), table_name='code_executions')
    op.drop_table('code_executions')
    op.drop_index(op.f('ix_tool_executions_task_id'), table_name='tool_executions')
    op.drop_index(op.f('ix_tool_executions_run_id'), table_name='tool_executions')
    op.drop_table('tool_executions')
    op.drop_index(op.f('ix_run_checkpoints_run_id'), table_name='run_checkpoints')
    op.drop_table('run_checkpoints')
    op.drop_index(op.f('ix_compliance_reviews_run_id'), table_name='compliance_reviews')
    op.drop_table('compliance_reviews')
    op.drop_index(op.f('ix_artifacts_run_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_mission_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_runs_plan_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_mission_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_plan_steps_plan_id'), table_name='plan_steps')
    op.drop_table('plan_steps')
    op.drop_index(op.f('ix_mission_plans_mission_id'), table_name='mission_plans')
    op.drop_table('mission_plans')
    op.drop_index(op.f('ix_knowledge_chunks_document_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_missions_workspace_id'), table_name='missions')
    op.drop_table('missions')
    op.drop_index(op.f('ix_knowledge_documents_workspace_id'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_users_identity_subject'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_audit_events_task_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_run_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_occurred_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_mission_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
