"""Export the FastAPI app's OpenAPI schema to JSON (ARCHITECTURE.md section
9: "OpenAPI is generated by FastAPI and is the source for TypeScript client
generation"). Run from apps/api; writes packages/shared/openapi.json."""

from __future__ import annotations

import json
from pathlib import Path

from app.main import app

OUTPUT_PATH = Path(__file__).resolve().parents[3] / "packages" / "shared" / "openapi.json"


def main() -> None:
    schema = app.openapi()
    OUTPUT_PATH.write_text(json.dumps(schema, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
